version: '3.4'

services:
  webapi1:
    image: ${DOCKER_REGISTRY-}webapi1
    build:
      context: .
      dockerfile: webAPI1/Dockerfile


  webapi2:
    image: ${DOCKER_REGISTRY-}webapi2
    build:
      context: .
      dockerfile: webAPI2/Dockerfile  